# LaTeX Tracker - Docker Setup
version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: latex_tracker_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: latex_tracker

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: latex_tracker_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - DB_NAME=latex_tracker
    volumes:
      - ./backend:/app
      - /tmp:/tmp

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: latex_tracker_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mongodb_data:
